version: '3'
services:

  pgdb-course:
    environment:
      - POSTGRES_DB=course
      - PGDATA=/var/lib/postgresql/data/course
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwer1234
    image: 'postgres:14-alpine'
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./pgdb:/docker-entrypoint-initdb.d:ro
